# Generated by Django 5.2.9 on 2025-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_text',
            field=models.CharField(blank=True, help_text='this is a test only', max_length=255),
        ),
    ]
